export const branchFork = (
	<svg
		aria-hidden='true'
		focusable='false'
		xmlns='http://www.w3.org/2000/svg'
		viewBox='0 0 20 20'
		width='20'
		height='20'
		fill='none'
	>
		<path
			d='M5.5 14.5v-3m0-6v6m0 0h8A1.5 1.5 0 0 0 15 10v-.5'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
		<circle
			cx='5.5'
			cy='17.5'
			r='1.5'
			fill='currentColor'
			fillOpacity='0.3'
			stroke='currentColor'
		/>
		<circle
			cx='5.5'
			cy='2.5'
			r='1.5'
			fill='currentColor'
			fillOpacity='0.3'
			stroke='currentColor'
		/>
		<circle
			cx='15'
			cy='6.5'
			r='1.5'
			fill='currentColor'
			fillOpacity='0.3'
			stroke='currentColor'
		/>
	</svg>
);
