export const containerHeight = (
	<svg
		aria-hidden='true'
		focusable='false'
		xmlns='http://www.w3.org/2000/svg'
		viewBox='0 0 20 20'
		width='20'
		height='20'
		fill='none'
	>
		<rect
			x='1'
			y='1'
			width='18'
			height='18'
			rx='1.5'
			stroke='currentColor'
			strokeOpacity='0.5'
			fill='none'
		/>
		<rect
			opacity='0.1'
			x='3'
			y='3'
			width='6'
			height='6'
			rx='0.5'
			fill='currentColor'
		/>
		<rect
			opacity='0.1'
			x='3'
			y='11'
			width='6'
			height='6'
			rx='0.5'
			fill='currentColor'
		/>
		<rect
			opacity='0.1'
			x='11'
			y='3'
			width='6'
			height='6'
			rx='0.5'
			fill='currentColor'
		/>
		<rect
			opacity='0.1'
			x='11'
			y='11'
			width='6'
			height='6'
			rx='0.5'
			fill='currentColor'
		/>
		<path
			d='m12 15-2 2m0 0-2-2m2 2v-4m2-8-2-2m0 0L8 5m2-2v4'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
	</svg>
);
