export const listUnordered = (
	<svg
		aria-hidden='true'
		focusable='false'
		xmlns='http://www.w3.org/2000/svg'
		viewBox='0 0 20 20'
		width='20'
		height='20'
		fill='none'
	>
		<path
			d='M9 3h9m-9 7h9m-9 7h9'
			stroke='currentColor'
			strokeOpacity='0.5'
			strokeLinecap='round'
			fill='none'
		/>
		<circle
			cx='4'
			cy='3'
			r='1.5'
			fill='currentColor'
			stroke='currentColor'
		/>
		<circle
			cx='4'
			cy='17'
			r='1.5'
			fill='currentColor'
			stroke='currentColor'
		/>
		<circle
			cx='4'
			cy='10'
			r='1.5'
			fill='currentColor'
			stroke='currentColor'
		/>
	</svg>
);
