export const sliders = (
	<svg
		xmlns='http://www.w3.org/2000/svg'
		viewBox='0 0 20 20'
		width='20'
		height='20'
		fill='none'
	>
		<rect
			x='12.5'
			y='2'
			width='3'
			height='4'
			rx='1'
			stroke='currentColor'
			strokeLinejoin='round'
			fill='none'
		/>
		<rect
			x='9.5'
			y='14'
			width='3'
			height='4'
			rx='1'
			stroke='currentColor'
			strokeLinejoin='round'
			fill='none'
		/>
		<path
			d='M1 4h11m7 0h-3'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
		a
		<path
			d='M1 10h3m15 0H8'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
		<rect
			x='4.5'
			y='8'
			width='3'
			height='4'
			rx='1'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
		<path
			d='M1 16h8m10 0h-6'
			stroke='currentColor'
			strokeLinecap='round'
			strokeLinejoin='round'
			fill='none'
		/>
	</svg>
);
